package com.shopflow.order.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Version;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

/**
 * WRITE-SIDE order state (CQRS command model).
 *
 * In this design the event store (OrderEventEntity) is the SOURCE OF TRUTH and
 * this row is the current-state SNAPSHOT the saga reads/updates. A purist
 * event-sourcing system would drop this table and always fold the events
 * (see OrderQueryController's /rebuilt endpoint for exactly that, live);
 * keeping a snapshot is the pragmatic middle ground most real systems use.
 */
@Entity
@Table(name = "orders")
public class OrderEntity {

    /** UUID generated by the app (not DB identity) so the id exists BEFORE the
     *  insert commits - we need it immediately for events and Kafka keys. */
    @Id
    private UUID id;

    @Column(nullable = false)
    private String userId;

    @Column(nullable = false)
    private String productId;

    @Column(nullable = false)
    private int quantity;

    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal totalAmount;

    @Enumerated(EnumType.STRING)   // store "PENDING", not ordinal 0 (ordinals break if enum order changes)
    @Column(nullable = false)
    private OrderStatus status;

    @Column(nullable = false)
    private Instant createdAt;

    private Instant updatedAt;

    /**
     * OPTIMISTIC LOCKING: Hibernate adds "WHERE version = ?" to updates and
     * throws OptimisticLockException if another transaction won the race.
     * Protects against concurrent saga-reply and timeout-sweep updates.
     */
    @Version
    private Long version;

    protected OrderEntity() {
    }

    public OrderEntity(UUID id, String userId, String productId, int quantity, BigDecimal totalAmount) {
        this.id = id;
        this.userId = userId;
        this.productId = productId;
        this.quantity = quantity;
        this.totalAmount = totalAmount;
        this.status = OrderStatus.PENDING;
        this.createdAt = Instant.now();
    }

    public void transitionTo(OrderStatus newStatus) {
        this.status = newStatus;
        this.updatedAt = Instant.now();
    }

    public UUID getId() { return id; }
    public String getUserId() { return userId; }
    public String getProductId() { return productId; }
    public int getQuantity() { return quantity; }
    public BigDecimal getTotalAmount() { return totalAmount; }
    public OrderStatus getStatus() { return status; }
    public Instant getCreatedAt() { return createdAt; }
    public Instant getUpdatedAt() { return updatedAt; }
}
